version: '3.8'
services:
  tfx_py3.10:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 8888:8888
    entrypoint: jupyter lab --ip='0.0.0.0' --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password=''
    container_name: tfx_py3.10
